In [4]:
import numpy as np

In [10]:
arr = np.arange(100)

In [11]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [52]:
ar=np.array([45,6,78,9.6,20,45], dtype='int32')

In [53]:
print(ar)

[45  6 78  9 20 45]


In [54]:
print(type(ar))

<class 'numpy.ndarray'>


In [55]:
ar.shape

(6,)

In [56]:
ar.dtype

dtype('int32')

In [73]:
array2=np.array([[1,3,5.9,7],[2,4,6,8]])
print(array2)

[[1.  3.  5.9 7. ]
 [2.  4.  6.  8. ]]


In [34]:
array2.shape

(2, 4)

In [35]:
array2.dtype

dtype('float64')

# Zeroes And Ones

In [39]:
zerod=np.zeros((4,6))
print(zerod)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [40]:
zerod.dtype

dtype('float64')

In [43]:
print(np.ones((4,6)))
np.ones(6).dtype

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


dtype('float64')

In [45]:
np.empty((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [46]:
array2*array2

array([[ 1.  ,  9.  , 34.81, 49.  ],
       [ 4.  , 16.  , 36.  , 64.  ]])

In [47]:
array2/array2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
1/array2

array([[1.        , 0.33333333, 0.16949153, 0.14285714],
       [0.5       , 0.25      , 0.16666667, 0.125     ]])

# Slicing

In [57]:
print(ar)

[45  6 78  9 20 45]


In [58]:
ar[4:6]

array([20, 45])

In [59]:
ar2=ar[4:6]

In [60]:
ar2

array([20, 45])

In [61]:
ar2[0]=56

In [62]:
ar

array([45,  6, 78,  9, 56, 45])

In [63]:
ar2

array([56, 45])

In [64]:
ar3=ar[4:6].copy()

In [65]:
ar3[0]=6

In [66]:
ar2

array([56, 45])

In [67]:
ar

array([45,  6, 78,  9, 56, 45])

In [68]:
ar3

array([ 6, 45])

In [70]:
array2

array([[1. , 3. , 5.9, 7. ],
       [2. , 4. , 6. , 8. ]])

In [74]:
array2[0,3]

7.0

# Tutorial 2

In [88]:
array3=np.array([[1,3,5], [2,4,6]])

# Axis

In [89]:
array3.sum(axis=1)   #row sum

array([ 9, 12])

In [90]:
array3.sum(axis=0)    #column sum

array([ 3,  7, 11])

In [118]:
b=np.array([[2,41,13],[16,17,18]])

In [119]:
array3.dot(b.transpose())

array([[190, 157],
       [246, 208]])

# To show numpy function

In [120]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [121]:
len(dir(np))

620

In [122]:
np.cross(array3,b)

array([[-166,   -3,   35],
       [ -30,   60,  -30]])

In [123]:
 np.sort(b)     # at axis 1

array([[ 2, 13, 41],
       [16, 17, 18]])

In [124]:
np.sort(b, axis=0)

array([[ 2, 17, 13],
       [16, 41, 18]])

# tutorial3

In [125]:
b

array([[ 2, 41, 13],
       [16, 17, 18]])

In [133]:
b=b.reshape(3,2) #it reshape the data

In [134]:
b

array([[ 2, 41],
       [13, 16],
       [17, 18]])

In [135]:
np.argsort(b)

array([[0, 1],
       [0, 1],
       [0, 1]], dtype=int32)

In [136]:
np.argmin(b)     # it give max place in index

0

In [137]:
np.argmax(b)

1

In [138]:
np.argsort(b, axis=0)

array([[0, 1],
       [1, 2],
       [2, 0]], dtype=int32)

# next panda tutorial